In [1]:
#Load libraries
import os
import pandas as pd
import numpy as np

Using TensorFlow backend.

In [3]:
test=pd.read_csv("test.csv")

In [4]:
test.describe()

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,9914.000000,9914.000000,9914.000000,9914.000000,9914.000000
mean,-73.974722,40.751041,-73.973657,40.751743,1.671273
std,0.042774,0.033541,0.039072,0.035435,1.278747
min,-74.252193,40.573143,-74.263242,40.568973,1.000000
25%,-73.992501,40.736125,-73.991247,40.735254,1.000000
50%,-73.982326,40.753051,-73.980015,40.754065,1.000000
75%,-73.968013,40.767113,-73.964059,40.768757,2.000000
max,-72.986532,41.709555,-72.990963,41.696683,6.000000

In [5]:
#Total number of missing values in each variables
missing_val = pd.DataFrame(test.isna().sum())
missing_val

                   0
pickup_datetime    0
pickup_longitude   0
pickup_latitude    0
dropoff_longitude  0
dropoff_latitude   0
passenger_count    0

In [ ]:
#Everything seems to be alright in test data - No wrong entries or missing values

In [6]:
#Converting pickup_datetime into datetime format
test['pickup_datetime']=pd.to_datetime(test['pickup_datetime'],format='%Y-%m-%d %H:%M:%S UTC')
test.head()

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,2015-01-27 13:08:24,-73.973320,40.763805,-73.981430,40.743835,1
1,2015-01-27 13:08:24,-73.986862,40.719383,-73.998886,40.739201,1
2,2011-10-08 11:53:44,-73.982524,40.751260,-73.979654,40.746139,1
3,2012-12-01 21:12:12,-73.981160,40.767807,-73.990448,40.751635,1
4,2012-12-01 21:12:12,-73.966046,40.789775,-73.988565,40.744427,1

In [7]:
data = [test]
for i in data:
    i['Year'] = i['pickup_datetime'].dt.year
    i['Month'] = i['pickup_datetime'].dt.month
    i['Date'] = i['pickup_datetime'].dt.day
    i['Day of Week'] = i['pickup_datetime'].dt.dayofweek
    i['Hour'] = i['pickup_datetime'].dt.hour

In [8]:
test

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,Year,Month,Date,Day of Week,Hour
0,2015-01-27 13:08:24,-73.973320,40.763805,-73.981430,40.743835,1,2015,1,27,1,13
1,2015-01-27 13:08:24,-73.986862,40.719383,-73.998886,40.739201,1,2015,1,27,1,13
2,2011-10-08 11:53:44,-73.982524,40.751260,-73.979654,40.746139,1,2011,10,8,5,11
3,2012-12-01 21:12:12,-73.981160,40.767807,-73.990448,40.751635,1,2012,12,1,5,21
4,2012-12-01 21:12:12,-73.966046,40.789775,-73.988565,40.744427,1,2012,12,1,5,21
5,2012-12-01 21:12:12,-73.960983,40.765547,-73.979177,40.740053,1,2012,12,1,5,21
6,2011-10-06 12:10:20,-73.949013,40.773204,-73.959622,40.770893,1,2011,10,6,3,12
7,2011-10-06 12:10:20,-73.777282,40.646636,-73.985083,40.759368,1,2011,10,6,3,12
8,2011-10-06 12:10:20,-74.014099,40.709638,-73.995106,40.741365,1,2011,10,6,3,12
9,2014-02-18 15:22:20,-73.969582,40.765519,-73.980686,40.770725,1,2014,2,18,1,15
10,2014-02-18 15:22:20,-73.989374,40.741973,-73.999300,40.722534,1,2014,2,18,1,15
11,2014-02-18 15:22:20,-74.001614,40.740893,-73.956387,40.767437,1,2014,2,18,1,15
12,2010-03-29 20:20:32,-73.991198,40.739937,-73.997166,40.735269,1,2010,3,29,0,20
13,2010-03-29 20:20:32,-73.982034,40.762723,-74.001867,40.761545,1,2010,3,29,0,20
14,2011-10-06 03:59:12,-73.992455,40.728701,-73.983397,40.750149,1,2011,10,6,3,3
15,2011-10-06 03:59:12,-73.983583,40.746993,-73.951178,40.785903,1,2011,10,6,3,3
16,2012-07-15 16:45:04,-74.006746,40.731721,-74.010204,40.732318,1,2012,7,15,6,16
17,2012-07-15 16:45:04,-73.976446,40.785598,-73.952220,40.772121,1,2012,7,15,6,16
18,2012-07-15 16:45:04,-73.973548,40.763349,-73.972096,40.756417,1,2012,7,15,6,16
19,2012-07-15 16:45:04,-73.970918,40.756025,-73.975954,40.755563,1,2012,7,15,6,16
20,2014-10-29 02:09:56,-73.926071,40.705866,-73.941741,40.714789,1,2014,10,29,2,2
21,2014-06-14 13:39:00,-73.970555,40.764702,-73.949132,40.771800,1,2014,6,14,5,13
22,2014-06-14 13:39:00,-73.989102,40.736360,-73.992767,40.747767,1,2014,6,14,5,13
23,2014-06-14 13:39:00,-74.003525,40.748480,-73.991520,40.762960,1,2014,6,14,5,13
24,2014-06-14 13:39:00,-73.990352,40.759992,-74.015665,40.711682,1,2014,6,14,5,13
25,2014-06-14 13:39:00,-73.989482,40.757450,-74.000850,40.762705,1,2014,6,14,5,13
26,2014-06-14 13:39:00,-73.870785,40.773722,-73.741922,40.689945,1,2014,6,14,5,13
27,2014-06-14 13:39:00,-73.992682,40.733877,-73.938852,40.808220,1,2014,6,14,5,13
28,2014-06-14 13:39:00,-73.954020,40.778705,-73.950277,40.768810,1,2014,6,14,5,13
29,2014-06-14 13:39:00,-73.972742,40.743432,-74.007125,40.710192,1,2014,6,14,5,13
...,...,...,...,...,...,...,...,...,...,...,...
9884,2013-09-25 22:00:00,-73.790022,40.643817,-73.735688,40.773400,6,2013,9,25,2,22
9885,2013-09-25 22:00:00,-74.007878,40.722762,-73.965740,40.754505,6,2013,9,25,2,22
9886,2013-09-25 22:00:00,-73.978852,40.752837,-73.941152,40.812722,6,2013,9,25,2,22
9887,2013-09-25 22:00:00,-73.959087,40.783282,-73.978802,40.785655,6,2013,9,25,2,22
9888,2013-09-25 22:00:00,-73.956488,40.767512,-73.956488,40.767512,6,2013,9,25,2,22
9889,2013-09-25 22:00:00,-73.966650,40.714675,-73.971912,40.693667,6,2013,9,25,2,22
9890,2013-09-25 22:00:00,-73.976602,40.754152,-73.993297,40.730887,6,2013,9,25,2,22
9891,2013-09-25 22:00:00,-73.987185,40.760505,-73.938755,40.799507,6,2013,9,25,2,22
9892,2013-09-25 22:00:00,-73.969175,40.757770,-73.952318,40.781030,6,2013,9,25,2,22
9893,2013-09-25 22:00:00,-73.949657,40.796197,-73.911755,40.827672,6,2013,9,25,2,22
9894,2013-09-25 22:00:00,-74.002267,40.730415,-73.990360,40.756807,6,2013,9,25,2,22
9895,2013-09-25 22:00:00,-73.985840,40.731167,-73.953883,40.653937,6,2013,9,25,2,22
9896,2013-09-25 22:00:00,-73.955490,40.776862,-73.982162,40.769302,6,2013,9,25,2,22
9897,2015-02-20 11:08:29,-73.965782,40.805538,-73.982384,40.761600,6,2015,2,20,4,11
9898,2015-01-12 15:36:37,-73.979042,40.777515,-73.983658,40.781082,6,2015,1,12,0,15
9899,2015-06-07 00:38:14,-73.983238,40.764874,-73.922928,40.743458,6,2015,6,7,6,0
9900,2015-04-12 21:56:22,-73.962952,40.772480,-73.976051,40.786289,6,2015,4,12,6,21
9901,2015-04-10 11:56:54,-73.977943,40.762753,-73.976219,40.776451,6,2015,4,10,4,11
9902,2015-06-25 01:01:46,-73.905525,40.752655,-73.864151,40.737091,6,2015,6,25,3,1
9903,2015-05-29 10:02:42,-73.988403,40.738731,-73.992340,40.759193,6,2015,5,29,4,10
9904,2015-06-30 20:03:50,-73.776848,40.645035,-73.955460,40.652458,6,2015,6,30,1,20
9905,2015-02-27 19:36:02,-73.989647,40.767406,-73.941177,40.845696,6,2015,2,27,4,19
9906,2015-06-15 01:00:06,-73.988052,40.720776,-73.991043,40.718346,6,2015,6,15,0,1
9907,2015-02-03 09:00:58,-73.863457,40.769611,-73.980995,40.763241,6,2015,2,3,1,9
9908,2015-05-19 13:58:11,-73.987968,40.718922,-73.982124,40.732956,6,2015,5,19,1,13
9909,2015-05-10 12:37:51,-73.968124,40.796997,-73.955643,40.780388,6,2015,5,10,6,12
9910,2015-01-12 17:05:51,-73.945511,40.803600,-73.960213,40.776371,6,2015,1,12,0,17
9911,2015-04-19 20:44:15,-73.991600,40.726608,-73.789742,40.647011,6,2015,4,19,6,20
9912,2015-01-31 01:05:19,-73.985573,40.735432,-73.939178,40.801731,6,2015,1,31,5,1
9913,2015-01-18 14:06:23,-73.988022,40.754070,-74.000282,40.759220,6,2015,1,18,6,14

In [9]:
def haversine_distance(lat1, long1, lat2, long2):
    data = [test]
    for i in data:
        R = 6371  #radius of earth in kilometers
        #R = 3959 #radius of earth in miles if u need calc in miles
        
        phi1 = np.radians(i[lat1])
        phi2 = np.radians(i[lat2])
    
        delta_phi = np.radians(i[lat2]-i[lat1])
        delta_lambda = np.radians(i[long2]-i[long1])
    
        #a = sin²((φB - φA)/2) + cos φA . cos φB . sin²((λB - λA)/2)
        a = np.sin(delta_phi / 2.0) ** 2 + np.cos(phi1) * np.cos(phi2) * np.sin(delta_lambda / 2.0) ** 2
    
        #c = 2 * atan2( √a, √(1−a) )
        c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1-a))
    
        #d = R*c
        d = (R * c) #in kilometers
        
        i['H_Distance'] = d
        
    return d

In [10]:
haversine_distance('pickup_latitude', 'pickup_longitude', 'dropoff_latitude', 'dropoff_longitude')

0        2.323259
1        2.425353
2        0.618628
3        1.961033
4        5.387301
5        3.222549
6        0.929601
7       21.540102
8        3.873962
9        1.099794
10       2.317685
11       4.819179
12       0.722670
13       1.675503
14       2.504032
15       5.115375
16       0.298838
17       2.531147
18       0.780444
19       0.427282
20       1.651946
21       1.969211
22       1.305441
23       1.901295
24       5.779720
25       1.121687
26      14.306540
27       9.427870
28       1.144529
29       4.696371
          ...
9884    15.119293
9885     5.006239
9886     7.376754
9887     1.680721
9888     0.000000
9889     2.377723
9890     2.944581
9891     5.952839
9892     2.950361
9893     4.735375
9894     3.101361
9895     9.000325
9896     2.398161
9897     5.081664
9898     0.555287
9899     5.610505
9900     1.890608
9901     1.530118
9902     3.891526
9903     2.299316
9904    15.091262
9905     9.613798
9906     0.369506
9907     9.923998
9908     1.636402
9909     2.124874
9910     3.270969
9911    19.183942
9912     8.343486
9913     1.180825
Length: 9914, dtype: float64

In [11]:
test

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,Year,Month,Date,Day of Week,Hour,H_Distance
0,2015-01-27 13:08:24,-73.973320,40.763805,-73.981430,40.743835,1,2015,1,27,1,13,2.323259
1,2015-01-27 13:08:24,-73.986862,40.719383,-73.998886,40.739201,1,2015,1,27,1,13,2.425353
2,2011-10-08 11:53:44,-73.982524,40.751260,-73.979654,40.746139,1,2011,10,8,5,11,0.618628
3,2012-12-01 21:12:12,-73.981160,40.767807,-73.990448,40.751635,1,2012,12,1,5,21,1.961033
4,2012-12-01 21:12:12,-73.966046,40.789775,-73.988565,40.744427,1,2012,12,1,5,21,5.387301
5,2012-12-01 21:12:12,-73.960983,40.765547,-73.979177,40.740053,1,2012,12,1,5,21,3.222549
6,2011-10-06 12:10:20,-73.949013,40.773204,-73.959622,40.770893,1,2011,10,6,3,12,0.929601
7,2011-10-06 12:10:20,-73.777282,40.646636,-73.985083,40.759368,1,2011,10,6,3,12,21.540102
8,2011-10-06 12:10:20,-74.014099,40.709638,-73.995106,40.741365,1,2011,10,6,3,12,3.873962
9,2014-02-18 15:22:20,-73.969582,40.765519,-73.980686,40.770725,1,2014,2,18,1,15,1.099794
10,2014-02-18 15:22:20,-73.989374,40.741973,-73.999300,40.722534,1,2014,2,18,1,15,2.317685
11,2014-02-18 15:22:20,-74.001614,40.740893,-73.956387,40.767437,1,2014,2,18,1,15,4.819179
12,2010-03-29 20:20:32,-73.991198,40.739937,-73.997166,40.735269,1,2010,3,29,0,20,0.722670
13,2010-03-29 20:20:32,-73.982034,40.762723,-74.001867,40.761545,1,2010,3,29,0,20,1.675503
14,2011-10-06 03:59:12,-73.992455,40.728701,-73.983397,40.750149,1,2011,10,6,3,3,2.504032
15,2011-10-06 03:59:12,-73.983583,40.746993,-73.951178,40.785903,1,2011,10,6,3,3,5.115375
16,2012-07-15 16:45:04,-74.006746,40.731721,-74.010204,40.732318,1,2012,7,15,6,16,0.298838
17,2012-07-15 16:45:04,-73.976446,40.785598,-73.952220,40.772121,1,2012,7,15,6,16,2.531147
18,2012-07-15 16:45:04,-73.973548,40.763349,-73.972096,40.756417,1,2012,7,15,6,16,0.780444
19,2012-07-15 16:45:04,-73.970918,40.756025,-73.975954,40.755563,1,2012,7,15,6,16,0.427282
20,2014-10-29 02:09:56,-73.926071,40.705866,-73.941741,40.714789,1,2014,10,29,2,2,1.651946
21,2014-06-14 13:39:00,-73.970555,40.764702,-73.949132,40.771800,1,2014,6,14,5,13,1.969211
22,2014-06-14 13:39:00,-73.989102,40.736360,-73.992767,40.747767,1,2014,6,14,5,13,1.305441
23,2014-06-14 13:39:00,-74.003525,40.748480,-73.991520,40.762960,1,2014,6,14,5,13,1.901295
24,2014-06-14 13:39:00,-73.990352,40.759992,-74.015665,40.711682,1,2014,6,14,5,13,5.779720
25,2014-06-14 13:39:00,-73.989482,40.757450,-74.000850,40.762705,1,2014,6,14,5,13,1.121687
26,2014-06-14 13:39:00,-73.870785,40.773722,-73.741922,40.689945,1,2014,6,14,5,13,14.306540
27,2014-06-14 13:39:00,-73.992682,40.733877,-73.938852,40.808220,1,2014,6,14,5,13,9.427870
28,2014-06-14 13:39:00,-73.954020,40.778705,-73.950277,40.768810,1,2014,6,14,5,13,1.144529
29,2014-06-14 13:39:00,-73.972742,40.743432,-74.007125,40.710192,1,2014,6,14,5,13,4.696371
...,...,...,...,...,...,...,...,...,...,...,...,...
9884,2013-09-25 22:00:00,-73.790022,40.643817,-73.735688,40.773400,6,2013,9,25,2,22,15.119293
9885,2013-09-25 22:00:00,-74.007878,40.722762,-73.965740,40.754505,6,2013,9,25,2,22,5.006239
9886,2013-09-25 22:00:00,-73.978852,40.752837,-73.941152,40.812722,6,2013,9,25,2,22,7.376754
9887,2013-09-25 22:00:00,-73.959087,40.783282,-73.978802,40.785655,6,2013,9,25,2,22,1.680721
9888,2013-09-25 22:00:00,-73.956488,40.767512,-73.956488,40.767512,6,2013,9,25,2,22,0.000000
9889,2013-09-25 22:00:00,-73.966650,40.714675,-73.971912,40.693667,6,2013,9,25,2,22,2.377723
9890,2013-09-25 22:00:00,-73.976602,40.754152,-73.993297,40.730887,6,2013,9,25,2,22,2.944581
9891,2013-09-25 22:00:00,-73.987185,40.760505,-73.938755,40.799507,6,2013,9,25,2,22,5.952839
9892,2013-09-25 22:00:00,-73.969175,40.757770,-73.952318,40.781030,6,2013,9,25,2,22,2.950361
9893,2013-09-25 22:00:00,-73.949657,40.796197,-73.911755,40.827672,6,2013,9,25,2,22,4.735375
9894,2013-09-25 22:00:00,-74.002267,40.730415,-73.990360,40.756807,6,2013,9,25,2,22,3.101361
9895,2013-09-25 22:00:00,-73.985840,40.731167,-73.953883,40.653937,6,2013,9,25,2,22,9.000325
9896,2013-09-25 22:00:00,-73.955490,40.776862,-73.982162,40.769302,6,2013,9,25,2,22,2.398161
9897,2015-02-20 11:08:29,-73.965782,40.805538,-73.982384,40.761600,6,2015,2,20,4,11,5.081664
9898,2015-01-12 15:36:37,-73.979042,40.777515,-73.983658,40.781082,6,2015,1,12,0,15,0.555287
9899,2015-06-07 00:38:14,-73.983238,40.764874,-73.922928,40.743458,6,2015,6,7,6,0,5.610505
9900,2015-04-12 21:56:22,-73.962952,40.772480,-73.976051,40.786289,6,2015,4,12,6,21,1.890608
9901,2015-04-10 11:56:54,-73.977943,40.762753,-73.976219,40.776451,6,2015,4,10,4,11,1.530118
9902,2015-06-25 01:01:46,-73.905525,40.752655,-73.864151,40.737091,6,2015,6,25,3,1,3.891526
9903,2015-05-29 10:02:42,-73.988403,40.738731,-73.992340,40.759193,6,2015,5,29,4,10,2.299316
9904,2015-06-30 20:03:50,-73.776848,40.645035,-73.955460,40.652458,6,2015,6,30,1,20,15.091262
9905,2015-02-27 19:36:02,-73.989647,40.767406,-73.941177,40.845696,6,2015,2,27,4,19,9.613798
9906,2015-06-15 01:00:06,-73.988052,40.720776,-73.991043,40.718346,6,2015,6,15,0,1,0.369506
9907,2015-02-03 09:00:58,-73.863457,40.769611,-73.980995,40.763241,6,2015,2,3,1,9,9.923998
9908,2015-05-19 13:58:11,-73.987968,40.718922,-73.982124,40.732956,6,2015,5,19,1,13,1.636402
9909,2015-05-10 12:37:51,-73.968124,40.796997,-73.955643,40.780388,6,2015,5,10,6,12,2.124874
9910,2015-01-12 17:05:51,-73.945511,40.803600,-73.960213,40.776371,6,2015,1,12,0,17,3.270969
9911,2015-04-19 20:44:15,-73.991600,40.726608,-73.789742,40.647011,6,2015,4,19,6,20,19.183942
9912,2015-01-31 01:05:19,-73.985573,40.735432,-73.939178,40.801731,6,2015,1,31,5,1,8.343486
9913,2015-01-18 14:06:23,-73.988022,40.754070,-74.000282,40.759220,6,2015,1,18,6,14,1.180825

In [12]:
test[(test.H_Distance==0)]

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,Year,Month,Date,Day of Week,Hour,H_Distance
121,2014-06-14 13:39:00,-73.980590,40.747682,-73.980590,40.747682,1,2014,6,14,5,13,0.0
279,2010-09-05 22:31:32,-74.047394,40.785789,-74.047394,40.785789,1,2010,9,5,6,22,0.0
318,2009-06-10 16:55:00,-73.985862,40.744027,-73.985862,40.744027,1,2009,6,10,2,16,0.0
417,2011-06-24 12:03:00,-73.964615,40.777620,-73.964615,40.777620,1,2011,6,24,4,12,0.0
423,2011-06-24 12:03:00,-73.955065,40.771505,-73.955065,40.771505,1,2011,6,24,4,12,0.0
434,2011-06-24 12:03:00,-73.960738,40.775717,-73.960738,40.775717,1,2011,6,24,4,12,0.0
451,2011-06-24 12:03:00,-73.967895,40.765477,-73.967895,40.765477,1,2011,6,24,4,12,0.0
491,2011-06-24 12:03:00,-73.830820,40.759288,-73.830820,40.759288,1,2011,6,24,4,12,0.0
498,2011-06-24 12:03:00,-73.945490,40.752820,-73.945490,40.752820,1,2011,6,24,4,12,0.0
666,2012-11-11 20:35:40,-73.970087,40.755266,-73.970087,40.755266,1,2012,11,11,6,20,0.0
781,2011-06-01 07:37:00,-73.989905,40.734030,-73.989905,40.734030,1,2011,6,1,2,7,0.0
860,2010-08-27 18:45:00,-73.999005,40.754848,-73.999005,40.754848,1,2010,8,27,4,18,0.0
943,2011-02-12 00:43:24,-73.971961,40.760160,-73.971961,40.760160,1,2011,2,12,5,0,0.0
976,2010-08-14 02:13:00,-73.990053,40.748000,-73.990053,40.748000,1,2010,8,14,5,2,0.0
981,2010-08-14 02:13:00,-73.992402,40.748773,-73.992402,40.748773,1,2010,8,14,5,2,0.0
1176,2010-09-29 16:43:00,-73.980442,40.760768,-73.980442,40.760768,1,2010,9,29,2,16,0.0
1189,2010-09-29 16:43:00,-73.964303,40.774320,-73.964303,40.774320,1,2010,9,29,2,16,0.0
1218,2010-09-29 16:43:00,-73.953045,40.809783,-73.953045,40.809783,1,2010,9,29,2,16,0.0
1245,2010-09-29 16:43:00,-73.924907,40.745833,-73.924907,40.745833,1,2010,9,29,2,16,0.0
1409,2012-11-03 17:11:00,-73.954875,40.769295,-73.954875,40.769295,1,2012,11,3,5,17,0.0
1429,2012-11-03 17:11:00,-73.953083,40.812757,-73.953083,40.812757,1,2012,11,3,5,17,0.0
1562,2011-06-20 09:55:24,-74.005821,40.735943,-74.005821,40.735943,1,2011,6,20,0,9,0.0
1706,2011-10-04 09:37:00,-73.906437,40.768967,-73.906437,40.768967,1,2011,10,4,1,9,0.0
1719,2011-10-04 09:37:00,-74.003757,40.739223,-74.003757,40.739223,1,2011,10,4,1,9,0.0
1742,2012-10-18 21:06:20,-73.962342,40.760760,-73.962342,40.760760,1,2012,10,18,3,21,0.0
1809,2014-04-21 16:00:36,-73.964849,40.766825,-73.964849,40.766825,1,2014,4,21,0,16,0.0
2071,2011-12-13 22:00:00,-73.956040,40.803803,-73.956040,40.803803,1,2011,12,13,1,22,0.0
2117,2011-12-13 22:00:00,-73.970485,40.749837,-73.970485,40.749837,1,2011,12,13,1,22,0.0
2131,2011-12-13 22:00:00,-73.988867,40.742575,-73.988867,40.742575,1,2011,12,13,1,22,0.0
2139,2012-03-12 09:50:24,-73.961687,40.760144,-73.961687,40.760144,1,2012,3,12,0,9,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6525,2010-05-02 12:39:55,-73.953666,40.767114,-73.953666,40.767114,1,2010,5,2,6,12,0.0
6826,2015-05-12 08:31:07,-73.894485,40.830456,-73.894485,40.830456,1,2015,5,12,1,8,0.0
6954,2010-03-20 21:35:20,-73.936749,40.748523,-73.936749,40.748523,2,2010,3,20,5,21,0.0
7163,2010-08-14 02:13:00,-74.046277,40.827915,-74.046277,40.827915,2,2010,8,14,5,2,0.0
7198,2010-09-29 16:43:00,-73.983923,40.774765,-73.983923,40.774765,2,2010,9,29,2,16,0.0
7322,2011-10-04 09:37:00,-73.940717,40.803238,-73.940717,40.803238,2,2011,10,4,1,9,0.0
7526,2011-03-06 21:01:00,-73.789468,40.654585,-73.789468,40.654585,2,2011,3,6,6,21,0.0
7607,2012-01-26 07:33:00,-73.958565,40.759662,-73.958565,40.759662,2,2012,1,26,3,7,0.0
7610,2012-01-26 07:33:00,-73.977613,40.748120,-73.977613,40.748120,2,2012,1,26,3,7,0.0
7637,2010-12-09 07:29:00,-73.980700,40.747953,-73.980700,40.747953,2,2010,12,9,3,7,0.0
7839,2012-12-15 06:35:45,-73.985492,40.698672,-73.985492,40.698672,2,2012,12,15,5,6,0.0
7874,2009-06-02 08:34:33,-73.978301,40.715627,-73.978301,40.715627,2,2009,6,2,1,8,0.0
7994,2013-01-19 20:19:45,-73.983774,40.729806,-73.983774,40.729806,2,2013,1,19,5,20,0.0
8159,2011-07-20 08:05:02,-74.046958,40.757302,-74.046958,40.757302,2,2011,7,20,2,8,0.0
8381,2009-07-30 15:49:15,-73.137393,41.366138,-73.137393,41.366138,2,2009,7,30,3,15,0.0
8424,2009-06-10 16:55:00,-73.988477,40.718737,-73.988477,40.718737,3,2009,6,10,2,16,0.0
8426,2011-06-24 12:03:00,-73.955625,40.779742,-73.955625,40.779742,3,2011,6,24,4,12,0.0
8517,2011-03-11 01:44:00,-73.982675,40.742583,-73.982675,40.742583,3,2011,3,11,4,1,0.0
8596,2010-09-20 16:48:00,-73.982960,40.724925,-73.982960,40.724925,3,2010,9,20,0,16,0.0
8632,2009-10-29 10:48:40,-73.996274,40.751946,-73.996274,40.751946,3,2009,10,29,3,10,0.0
8835,2012-12-01 21:12:12,-73.880419,40.741367,-73.880419,40.741367,4,2012,12,1,5,21,0.0
9006,2013-07-02 22:27:14,-73.988070,40.622553,-73.988070,40.622553,4,2013,7,2,1,22,0.0
9221,2010-08-27 18:45:00,-73.971985,40.745787,-73.971985,40.745787,5,2010,8,27,4,18,0.0
9383,2011-03-11 01:44:00,-73.957203,40.774993,-73.957203,40.774993,5,2011,3,11,4,1,0.0
9421,2011-10-04 09:37:00,-73.982497,40.754883,-73.982497,40.754883,5,2011,10,4,1,9,0.0
9478,2011-12-13 22:00:00,-73.946078,40.749467,-73.946078,40.749467,5,2011,12,13,1,22,0.0
9500,2014-07-21 18:19:00,-73.975767,40.752947,-73.975767,40.752947,5,2014,7,21,0,18,0.0
9563,2011-03-06 21:01:00,-73.990780,40.724202,-73.990780,40.724202,5,2011,3,6,6,21,0.0
9830,2014-07-21 18:19:00,-73.981425,40.773935,-73.981425,40.773935,6,2014,7,21,0,18,0.0
9888,2013-09-25 22:00:00,-73.956488,40.767512,-73.956488,40.767512,6,2013,9,25,2,22,0.0

In [13]:
#Removing distances with 0 value 
test=test.drop(test[(test.H_Distance==0)].index,axis=0)

In [14]:
test.shape

(9829, 12)

In [15]:
test=test.drop("pickup_datetime",axis=1)

In [16]:
test

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,Year,Month,Date,Day of Week,Hour,H_Distance
0,-73.973320,40.763805,-73.981430,40.743835,1,2015,1,27,1,13,2.323259
1,-73.986862,40.719383,-73.998886,40.739201,1,2015,1,27,1,13,2.425353
2,-73.982524,40.751260,-73.979654,40.746139,1,2011,10,8,5,11,0.618628
3,-73.981160,40.767807,-73.990448,40.751635,1,2012,12,1,5,21,1.961033
4,-73.966046,40.789775,-73.988565,40.744427,1,2012,12,1,5,21,5.387301
5,-73.960983,40.765547,-73.979177,40.740053,1,2012,12,1,5,21,3.222549
6,-73.949013,40.773204,-73.959622,40.770893,1,2011,10,6,3,12,0.929601
7,-73.777282,40.646636,-73.985083,40.759368,1,2011,10,6,3,12,21.540102
8,-74.014099,40.709638,-73.995106,40.741365,1,2011,10,6,3,12,3.873962
9,-73.969582,40.765519,-73.980686,40.770725,1,2014,2,18,1,15,1.099794
10,-73.989374,40.741973,-73.999300,40.722534,1,2014,2,18,1,15,2.317685
11,-74.001614,40.740893,-73.956387,40.767437,1,2014,2,18,1,15,4.819179
12,-73.991198,40.739937,-73.997166,40.735269,1,2010,3,29,0,20,0.722670
13,-73.982034,40.762723,-74.001867,40.761545,1,2010,3,29,0,20,1.675503
14,-73.992455,40.728701,-73.983397,40.750149,1,2011,10,6,3,3,2.504032
15,-73.983583,40.746993,-73.951178,40.785903,1,2011,10,6,3,3,5.115375
16,-74.006746,40.731721,-74.010204,40.732318,1,2012,7,15,6,16,0.298838
17,-73.976446,40.785598,-73.952220,40.772121,1,2012,7,15,6,16,2.531147
18,-73.973548,40.763349,-73.972096,40.756417,1,2012,7,15,6,16,0.780444
19,-73.970918,40.756025,-73.975954,40.755563,1,2012,7,15,6,16,0.427282
20,-73.926071,40.705866,-73.941741,40.714789,1,2014,10,29,2,2,1.651946
21,-73.970555,40.764702,-73.949132,40.771800,1,2014,6,14,5,13,1.969211
22,-73.989102,40.736360,-73.992767,40.747767,1,2014,6,14,5,13,1.305441
23,-74.003525,40.748480,-73.991520,40.762960,1,2014,6,14,5,13,1.901295
24,-73.990352,40.759992,-74.015665,40.711682,1,2014,6,14,5,13,5.779720
25,-73.989482,40.757450,-74.000850,40.762705,1,2014,6,14,5,13,1.121687
26,-73.870785,40.773722,-73.741922,40.689945,1,2014,6,14,5,13,14.306540
27,-73.992682,40.733877,-73.938852,40.808220,1,2014,6,14,5,13,9.427870
28,-73.954020,40.778705,-73.950277,40.768810,1,2014,6,14,5,13,1.144529
29,-73.972742,40.743432,-74.007125,40.710192,1,2014,6,14,5,13,4.696371
...,...,...,...,...,...,...,...,...,...,...,...
9883,-73.993570,40.696330,-74.007182,40.728030,6,2013,9,25,2,22,3.706892
9884,-73.790022,40.643817,-73.735688,40.773400,6,2013,9,25,2,22,15.119293
9885,-74.007878,40.722762,-73.965740,40.754505,6,2013,9,25,2,22,5.006239
9886,-73.978852,40.752837,-73.941152,40.812722,6,2013,9,25,2,22,7.376754
9887,-73.959087,40.783282,-73.978802,40.785655,6,2013,9,25,2,22,1.680721
9889,-73.966650,40.714675,-73.971912,40.693667,6,2013,9,25,2,22,2.377723
9890,-73.976602,40.754152,-73.993297,40.730887,6,2013,9,25,2,22,2.944581
9891,-73.987185,40.760505,-73.938755,40.799507,6,2013,9,25,2,22,5.952839
9892,-73.969175,40.757770,-73.952318,40.781030,6,2013,9,25,2,22,2.950361
9893,-73.949657,40.796197,-73.911755,40.827672,6,2013,9,25,2,22,4.735375
9894,-74.002267,40.730415,-73.990360,40.756807,6,2013,9,25,2,22,3.101361
9895,-73.985840,40.731167,-73.953883,40.653937,6,2013,9,25,2,22,9.000325
9896,-73.955490,40.776862,-73.982162,40.769302,6,2013,9,25,2,22,2.398161
9897,-73.965782,40.805538,-73.982384,40.761600,6,2015,2,20,4,11,5.081664
9898,-73.979042,40.777515,-73.983658,40.781082,6,2015,1,12,0,15,0.555287
9899,-73.983238,40.764874,-73.922928,40.743458,6,2015,6,7,6,0,5.610505
9900,-73.962952,40.772480,-73.976051,40.786289,6,2015,4,12,6,21,1.890608
9901,-73.977943,40.762753,-73.976219,40.776451,6,2015,4,10,4,11,1.530118
9902,-73.905525,40.752655,-73.864151,40.737091,6,2015,6,25,3,1,3.891526
9903,-73.988403,40.738731,-73.992340,40.759193,6,2015,5,29,4,10,2.299316
9904,-73.776848,40.645035,-73.955460,40.652458,6,2015,6,30,1,20,15.091262
9905,-73.989647,40.767406,-73.941177,40.845696,6,2015,2,27,4,19,9.613798
9906,-73.988052,40.720776,-73.991043,40.718346,6,2015,6,15,0,1,0.369506
9907,-73.863457,40.769611,-73.980995,40.763241,6,2015,2,3,1,9,9.923998
9908,-73.987968,40.718922,-73.982124,40.732956,6,2015,5,19,1,13,1.636402
9909,-73.968124,40.796997,-73.955643,40.780388,6,2015,5,10,6,12,2.124874
9910,-73.945511,40.803600,-73.960213,40.776371,6,2015,1,12,0,17,3.270969
9911,-73.991600,40.726608,-73.789742,40.647011,6,2015,4,19,6,20,19.183942
9912,-73.985573,40.735432,-73.939178,40.801731,6,2015,1,31,5,1,8.343486
9913,-73.988022,40.754070,-74.000282,40.759220,6,2015,1,18,6,14,1.180825

In [17]:
test.shape

(9829, 11)

In [ ]:
test.to_csv("test_clean.csv",index=False)